version: "3.8"
services:
  config-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-transaction-service
    restart: always
    ports:
      - 8884:8884
    networks:
      app_subnet:
        aliases:
          - app_subnet
networks:
  app_subnet:
    name: network_mongo
    external: true